main/urls.py
from django.urls import path
from main.views import create_product_flutter, show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id , register, login_user, logout_user, increase, decrease, delete, edit_product, get_product_json, add_product_ajax




app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('increase/<int:id>', increase, name='increase'),
    path('decrease/<int:id>', decrease, name='decrease'),
    path('delete/<int:id>', delete, name='delete'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-product/<int:id>', edit_product, name='edit_product'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

tugas_2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Product(models.Model):
    myname = models.CharField(max_length=255, default='')
    myclass = models.CharField(max_length=255, default='')
    title = models.CharField(max_length=255, default='')
    description = models.TextField()
    amount = models.IntegerField()
    date_added = models.DateField(auto_now=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.CharField(max_length=255, default='')

main/forms.py
from django.forms import ModelForm
from main.models import Product

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["title", "description", "amount", "image"]

main/views.py
import json
from django.shortcuts import render
from django.http import HttpResponseNotFound, HttpResponseRedirect, JsonResponse
from main.forms import ProductForm
from django.urls import reverse
from django.http import HttpResponse
from django.core import serializers
from main.models import Product
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.views.decorators.csrf import csrf_exempt


# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    products = Product.objects.filter(user=request.user)
    context = {
        'myname': request.user.username,
        'myclass': 'PBP B',
        'title': 'Six of Crows',
        'description': 'Genre: Young Adult Fantasy',
        'amount': 5,
        'products': products,
        'last_login': request.COOKIES['last_login']

    }

    return render(request, "main.html", context)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_product.html", context)

def increase(request, id):
    product = Product.objects.get(pk=id)
    product.amount += 1
    product.save()
    response = HttpResponseRedirect(reverse("main:show_main")) 
    return response

def decrease(request, id):
    product = Product.objects.get(pk=id)
    response = HttpResponseRedirect(reverse("main:show_main"))
    if (product.amount == 0):
        return response
    product.amount -= 1
    product.save() 
    return response

def delete(request, id):
    product = Product.objects.get(pk=id)
    product.delete()
    response = HttpResponseRedirect(reverse("main:show_main"))
    return response

def increase(request, id):
    product = Product.objects.get(pk=id)
    product.amount += 1
    product.save()
    response = HttpResponseRedirect(reverse("main:show_main")) 
    return response

def show_xml(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_product(request, id):
    # Get product berdasarkan ID
    product = Product.objects.get(pk = id)

    # Set product sebagai instance dari form
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def get_product_json(request):
    product_item = Product.objects.all()
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        title = request.POST.get("title")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        user = request.user

        new_product = Product(title=title, amount=amount, description=description, user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Product.objects.create(
            user = request.user,
            title = data["title"],
            amount = int(data["amount"]),
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_product.html
{% extends 'base.html' %} 

{% block meta %}
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <title>Add New Product</title>
    <style>
        body{
            background-color: #5E4A41;
        }
        .tablestyle {
            position: absolute;
            top: 50%;
            left: 50%;
            margin-top: 150px;
            transform: translate(-50%,-50%);
            width: 900px;
            min-height: 100px;
            background: #5E4A41;
            border-radius: 30px;
            padding: 40px;
            box-sizing: border-box;
            font-family: 'Poppins',sans-serif;
            color: #3A2D27;
            text-align: left;
            box-shadow: -3px -3px 7px #906F60,
                        2px 2px 5px #3A2D27;
    } 

    .tablestyle input[type="text"],
    .tablestyle input[type="number"],
    .tablestyle textarea {
    width: 100%;
    padding: 10px;
    border: none;
    background-color: #5E4A41;
    border-radius: 10px;
    margin-bottom: 10px;
        color: #3A2D27;
        box-shadow: inset 2px 2px 5px #906F60,
                    inset -5px -5px 10px #3A2D27;
    }

    .tablestyle input[type="submit"] {
        margin: 15px 0;
        width: 100%;
        height: 50px;
        font-size: 18px;
        line-height: 50px;
        font-weight: 600;
        background: #5E4A41;
        border-radius: 25px;
        border: none;
        outline: none;
        cursor: pointer;
        color: #271E1A;
        box-shadow: 2px 2px 5px #906F60,
                    -5px -5px 10px #3A2D27;
    }

    .tablestyle input[type="submit"]:hover {
        color: #271E1A;
        box-shadow: inset 2px 2px 5px #906F60,
                    inset -5px -5px 10px #3A2D27;
    }

    .header {
        font-family: 'Poppins',sans-serif;
        text-align: center;
        margin-top: 20px;
        color: #070707;
        margin-bottom: 50px;
        
    }


    </style>


{% endblock meta %}

{% block content %}

<div class="header">
    <h1>Add New Product</h1>
</div>

<form method="POST">
    {% csrf_token %}
    <div class = "tablestyle">
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>

                <input type="submit" value="Add New Product"/>
            </td>
        </tr>
    </table>
</div>
</form>

{% endblock content %}

main/templates/edit_product.html
{% extends 'base.html' %}

{% block meta %}
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <title>Edit Product</title>
    <style>
        body{
            background-color: #5E4A41;
        }
        .tablestyle {
            position: absolute;
            top: 50%;
            left: 50%;
            margin-top: 150px;
            transform: translate(-50%,-50%);
            width: 900px;
            min-height: 100px;
            background: #5E4A41;
            border-radius: 30px;
            padding: 40px;
            box-sizing: border-box;
            font-family: 'Poppins',sans-serif;
            color: #3A2D27;
            text-align: left;
            box-shadow: -3px -3px 7px #906F60,
                        2px 2px 5px #3A2D27;
    } 

    .tablestyle input[type="text"],
    .tablestyle input[type="number"],
    .tablestyle textarea {
    width: 100%;
    padding: 10px;
    border: none;
    background-color: #5E4A41;
    border-radius: 10px;
    margin-bottom: 10px;
        color: #3A2D27;
        box-shadow: inset 2px 2px 5px #906F60,
                    inset -5px -5px 10px #3A2D27;
    }

    .tablestyle input[type="submit"] {
        margin: 15px 0;
        width: 100%;
        height: 50px;
        font-size: 18px;
        line-height: 50px;
        font-weight: 600;
        background: #5E4A41;
        border-radius: 25px;
        border: none;
        outline: none;
        cursor: pointer;
        color: #271E1A;
        box-shadow: 2px 2px 5px #906F60,
                    -5px -5px 10px #3A2D27;
    }

    .tablestyle input[type="submit"]:hover {
        color: #271E1A;
        box-shadow: inset 2px 2px 5px #906F60,
                    inset -5px -5px 10px #3A2D27;
    }

    .header {
        font-family: 'Poppins',sans-serif;
        text-align: center;
        margin-top: 20px;
        color: #070707;
        margin-bottom: 50px;
        
    }


    </style>


{% endblock meta %}


{% block content %}

<h1>Edit Product</h1>

<form method="POST">
    {% csrf_token %}
    <div class="tablestyle">
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Edit Product"/>
            </td>
        </tr>
    </table>
</div>
</form>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}
<head>
    <meta charset="utf-8">
    <!-- <title>Neumorphism Login Form UI | CodingNepal</title> -->
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
    <style>
        @import url('https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap');
        *{
        margin: 0;
        padding: 0;
        /* user-select: none; */
        box-sizing: border-box;
        font-family: 'Poppins', sans-serif;
        }
        html,body{
        height: 100%;
        }
        body{
        display: grid;
        place-items: center;
        background-image: url("https://img.freepik.com/free-photo/high-anglebeautiful-love-letters_23-2150716544.jpg?w=826&t=st=1696329293~exp=1696329893~hmac=a091cd22f63caba78c65d395a8ca7e82d91615ff0d2368c9c4afc8087c70a07b");
        background-size: cover; 
        background-repeat: no-repeat;
        background-attachment: fixed;
        /* background: #dde1e7; */
        text-align: center;
        }
        .content{
        width: 330px;
        padding: 40px 30px;
        background: #5E4A41;
        border-radius: 10px;
        box-shadow: -3px -3px 7px #906F60,
                    2px 2px 5px #3A2D27;
        }
        .content .text{
        font-size: 33px;
        font-weight: 600;
        margin-bottom: 35px;
        color: #271E1A;
        }
        .field{
        height: 50px;
        width: 100%;
        display: flex;
        position: relative;
        }
        .field:nth-child(2){
        margin-top: 20px;
        }
        .field input{
        height: 100%;
        width: 100%;
        padding-left: 45px;
        outline: none;
        border: none;
        font-size: 18px;
        background: #5E4A41;
        color: #3A2D27;
        border-radius: 25px;
        box-shadow: inset 2px 2px 5px #906F60,
                    inset -5px -5px 10px #3A2D27;
        }
        .field input:focus{
        box-shadow: inset 1px 1px 2px #906F60,
                    inset -1px -1px 2px #3A2D27;
        }
        .field span{
        position: absolute;
        color: #3A2D27;
        width: 50px;
        line-height: 50px;
        }
        .field label{
        position: absolute;
        top: 50%;
        transform: translateY(-50%);
        left: 45px;
        pointer-events: none;
        color: #271E1A;
        }
        .field input:valid ~ label{
        opacity: 0;
        }

        button{
        margin: 15px 0;
        width: 100%;
        height: 50px;
        font-size: 18px;
        line-height: 50px;
        font-weight: 600;
        background: #5E4A41;
        border-radius: 25px;
        border: none;
        outline: none;
        cursor: pointer;
        color: #271E1A;
        box-shadow: 2px 2px 5px #906F60,
                    -5px -5px 10px #3A2D27;
        }
        button:focus{
        color: #271E1A;
        box-shadow: inset 2px 2px 5px #906F60,
                    inset -5px -5px 10px #3A2D27;
        }
        .sign-up{
        margin: 10px 0;
        color: #271E1A;
        font-size: 16px;
        }
        .sign-up a{
        color: #3498db;
        text-decoration: none;
        }
        .sign-up a:hover{
        text-decoration: underline;
        }
        input::placeholder{
        color : #271E1A"
        }
    </style>
</head>
<body>
    <div class="content">
        <div class="text">
           Login Form
        </div>
        <form method="POST" action="">
            {% csrf_token %}
            <div class="field">
                <input type="text" name="username" placeholder="Username">
                <span class="fas fa-user"></span>
                <!-- <label>Username</label> -->
            </div>
            <div class="field">
                <input type="password" name="password" placeholder="Password">
                <span class="fas fa-lock"></span>
                <!-- <label>Password</label> -->
            </div>
            <button type="submit">Login</button>
            <div class="sign-up">
                Don't have an account yet?
                <a href="{% url 'main:register' %}">Register Now</a>
            </div>
        </form>

        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}  
    </div>
</body>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}
    <head>
        <style>
            @import url('https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap');
            *{
            font-family: 'Poppins', sans-serif;
            }
            :root {
            --surface-color: #5E4A41;
            --curve: 40;
            }

            * {
            box-sizing: border-box;
            }

            body {
            /* font-family: 'Noto Sans JP', sans-serif; */
            background-color: #5E4A41;
            }

            .cards {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 1rem;
            margin: 2rem 3vw;
            padding: 0;
            list-style-type: none;
            }

            .card {
            background-color: #5E4A41;
            position: relative;
            display: block;
            height: 500px;  
            /* width: 15px; */
            border: 1px solid #5E4A41;
            border-radius: 30px;
            overflow: hidden;
            text-decoration: none;
            box-shadow: inset 2px 2px 5px #906F60,
                    inset -5px -5px 10px #3A2D27,
                    2px 2px 5px #906F60,
                    -5px -5px 10px #3A2D27;;
            }

            .card__image {      
            width: 100%;
            height: auto;
            }

            .card__overlay {
            position: absolute;
            bottom: 0;
            left: 0;
            right: 0;
            z-index: 1;      
            border-radius: calc(var(--curve) * 1px);    
            background-color: var(--surface-color);      
            transform: translateY(100%);
            transition: .2s ease-in-out;
            }

            .card:hover .card__overlay {
            transform: translateY(0);
            padding: 50px;
            }

            .card__header {
            position: relative;
            display: flex;
            align-items: center;
            gap: 2em;
            padding: 2em;
            border-radius: calc(var(--curve) * 1px) 0 0 0;    
            background-color: var(--surface-color);
            transform: translateY(-100%);
            transition: .2s ease-in-out;
            }

            .card__arc {
            width: 80px;
            height: 80px;
            position: absolute;
            bottom: 100%;
            right: 0;      
            z-index: 1;
            }

            .card__arc path {
            fill: var(--surface-color);
            d: path("M 40 80 c 22 0 40 -22 40 -40 v 40 Z");
            }       

            .card:hover .card__header {
            transform: translateY(0);
            }

            .card__thumb {
            flex-shrink: 0;
            width: 50px;
            height: 50px;      
            border-radius: 50%;      
            }

            .card__title {
            font-size: 1em;
            margin: 0 0 .3em;
            color: #271E1A;
            }

            .card__tagline {
            display: block;
            margin: 1em 0;
            /* font-family: "MockFlowFont";   */
            font-size: .8em; 
            color: #271E1A;  
            }

            .card__status {
            font-size: .8em;
            color: #271E1A;
            }

            .card__description {
            padding: 0 2em 2em;
            margin: 0;
            color: #271E1A;
            /* font-family: "MockFlowFont";    */
            display: -webkit-box;
            -webkit-box-orient: vertical;
            -webkit-line-clamp: 3;
            overflow: hidden;
            }
            .navbar{
                width: 100%;
                color: #271E1A;
                background-color: #5E4A41;
                box-shadow: 2px 2px 5px #906F60,
                    -5px -5px 10px #3A2D27;
            }    

            .stok{
                font-size: 1em;
                margin: 15px;
                color: #271E1A;
            }

            button{
                margin: 2px;
                width: 100%;
                height: 50px;
                font-size: 18px;
                line-height: 50px;
                font-weight: 600;
                background: #5E4A41;
                border-radius: 25px;
                border: none;
                outline: none;
                cursor: pointer;
                color: #271E1A;
                box-shadow: 2px 2px 5px #906F60,
                            -5px -5px 10px #3A2D27;
            }
            button:focus{
            color: #271E1A;
            box-shadow: inset 2px 2px 5px #906F60,
                        inset -5px -5px 10px #3A2D27;
            }
            #newproduct{
                width: 200px;
            }
            .last_item .card__overlay{
                background: #906;
            }
        </style>
    </head>

    <body>
        <table>
            <tr>
                <div class="navbar">
                    <h1>Centaur Library</h1>
                    <a href="{% url 'main:logout' %}">
                        <button class="logout-button">Logout</button>
                    </a>
                </div>
            </tr>
        </table>
        <ul class="cards" id="product_table"></ul>
        <a href="{% url 'main:create_product' %}">
            <button id="newproduct">Add New Product</button>
        </a>
        
        <p class="card__description">Sesi terakhir login: {{ last_login }}</p>

        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form id="form" onsubmit="return false;">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="name" class="col-form-label">Name:</label>
                                <input type="text" class="form-control" id="name" name="name"></input>
                            </div>
                            <div class="mb-3">
                                <label for="amount" class="col-form-label">Amount:</label>
                                <input type="number" class="form-control" id="amount" name="amount"></input>
                            </div>
                            <div class="mb-3">
                                <label for="description" class="col-form-label">Description:</label>
                                <textarea class="form-control" id="description" name="description"></textarea>
                            </div>
                            <div class="mb-3">
                                <label for="image" class="col-form-label">Image:</label>
                                <input type="url" class="form-control" id="image" name="image"></input>
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
                    </div>
                </div>
            </div>
        </div>
    
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Product by AJAX</button>
    
        <script>
            function addProduct() {
            fetch("{% url 'main:add_product_ajax' %}", {
                method: "POST",
                body: new FormData(document.querySelector('#form'))
            }).then(refreshProducts)
    
            document.getElementById("form").reset()
            return false
            }
    
            document.getElementById("button_add").onclick = addProduct
    
            async function getProducts() {
                return fetch("{% url 'main:get_product_json' %}").then((res) => res.json())
            }
    
            async function refreshProducts() {
            document.getElementById("product_table").innerHTML = ""
            const products = await getProducts()
            let htmlString = ``
            products.forEach((item) => {
                htmlString += `
                <li class="{% if forloop.last %}last_item{% endif %}">
                    <a href="" class="card">
                        <img src="${item.fields.image}" class="card__image"/>
                        <div class="card__overlay">
                            <div class="card__header">
                                <div class="card__header-text">
                                    <h3 class="card__title">${item.fields.title}</h3>            
                                    <span class="card__status">Date Added: ${item.fields.date_added}</span>
                                </div>
                            </div>
                            <table>
                                <tr><p class="card__description">${item.fields.description}</p></td>
                                <tr>
                                    <h3 class="card__title">Stok:</h3>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="decrease/${item.pk}">
                                            <button>-</button>
                                        </a>
                                    </td>
                                    <td>
                                        <h3 class="stok">${item.fields.amount}</h3>
                                    </td>
                                    <td>
                                        <a href="increase/${item.pk}">
                                            <button>+</button>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="edit-product/${item.pk}">
                                        <button>Edit</button>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="delete/${item.pk}">
                                            <button>Delete</button>
                                        </a>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </a>      
                </li>
                ` 
            })
            
            document.getElementById("product_table").innerHTML = htmlString
        }
    
        refreshProducts()
    
        </script>

    </body>


    
{% endblock content %}

<!-- {% for product in products %}
            <li class="{% if forloop.last %}last_item{% endif %}">
                <a href="{{ product.url }}" class="card">
                    <img src="{{ product.image }}" class="card__image"/>
                    <div class="card__overlay">
                        <div class="card__header">
                            <div class="card__header-text">
                                <h3 class="card__title">{{ product.title }}</h3>            
                                <span class="card__status">Date Added: {{ product.date_added }}</span>
                            </div>
                        </div>
                        <table>
                            <tr><p class="card__description">{{ product.description }}</p></td>
                            <tr>
                                <h3 class="card__title">Stok:</h3>
                            </tr>
                            <tr>
                                <td>
                                    <a href="{% url 'main:decrease' product.id %}">
                                        <button>-</button>
                                    </a>
                                </td>
                                <td>
                                    <h3 class="stok">{{ product.amount }}</h3>
                                </td>
                                <td>
                                    <a href="{% url 'main:increase' product.id %}">
                                        <button>+</button>
                                    </a>
                                </td>
                                <td>
                                    <a href="{% url 'main:edit_product' product.pk %}">
                                    <button>Edit</button>
                                    </a>
                                </td>
                                <td>
                                    <a href="{% url 'main:delete' product.id %}">
                                        <button>Delete</button>
                                    </a>
                                </td>
                            </tr>
                        </table>
                    </div>
                </a>      
            </li>
            {% endfor %}

            \n<tr>
                <td>${item.fields.name}</td>
                <td>${item.fields.price}</td>
                <td>${item.fields.description}</td>
                <td>${item.fields.date_added}</td>
            </tr> -->